In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('DraftData.csv')
df.head()

,Draft_Year,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Receive_TD,Solo,Int,Sk,College_Univ,College Stats,Prospect_Grade,College Stats URL,Unnamed: 32,Unnamed: 33
0,2014.0,1.0,1.0,HOU,Jadeveon Clowney,DE,21.0,2024.0,0.0,3.0,...,0.0,272.0,1.0,58.0,South Carolina,College Stats,7.5,http://www.sports-reference.com/cfb/players/ja...,NaN,NaN
1,2014.0,1.0,2.0,STL,Greg Robinson,T,21.0,2019.0,0.0,0.0,...,0.0,NaN,NaN,NaN,Auburn,College Stats,7.0,http://www.sports-reference.com/cfb/players/gr...,NaN,NaN
2,2014.0,1.0,3.0,JAX,Blake Bortles,QB,22.0,2019.0,0.0,0.0,...,1.0,NaN,NaN,NaN,Central Florida,College Stats,6.8,http://www.sports-reference.com/cfb/players/bl...,NaN,NaN
3,2014.0,1.0,4.0,BUF,Sammy Watkins,WR,21.0,2022.0,0.0,0.0,...,34.0,1.0,NaN,NaN,Clemson,College Stats,7.1,http://www.sports-reference.com/cfb/players/sa...,NaN,NaN
4,2014.0,1.0,5.0,OAK,Khalil Mack,LB,23.0,2024.0,3.0,9.0,...,0.0,462.0,3.0,107.5,Buffalo,College Stats,7.0,http://www.sports-reference.com/cfb/players/kh...,NaN,NaN

In [8]:
df[['College Stats URL']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1593 entries, 0 to 1592
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   College Stats URL  683 non-null    object
dtypes: object(1)
memory usage: 12.6+ KB

In [9]:
df.dropna(subset=['College Stats URL'], inplace=True)
df[['College Stats URL']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 683 entries, 0 to 700
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   College Stats URL  683 non-null    object
dtypes: object(1)
memory usage: 10.7+ KB

In [13]:
df['Player'].value_counts()

Player
Byron Murphy          2
Christian Darrisaw    1
Mac Jones             1
Zaven Collins         1
Alex Leatherwood      1
                     ..
Marcus Williams       1
Sidney Jones          1
Gerald Everett        1
Quincy Wilson         1
Kingsley Suamataia    1
Name: count, Length: 682, dtype: int64

In [16]:
df[df['Player']  == 'Byron Murphy']

,Draft_Year,Rnd,Pick,Tm,Player,Pos,Age,To,AP1,PB,...,Receive_TD,Solo,Int,Sk,College_Univ,College Stats,Prospect_Grade,College Stats URL,Unnamed: 32,Unnamed: 33
351,2019.0,2.0,33.0,ARI,Byron Murphy,CB,21.0,2024.0,0.0,1.0,...,0.0,289.0,14.0,3.0,Washington,College Stats,6.40,http://www.sports-reference.com/cfb/players/by...,NaN,NaN
653,2024.0,1.0,16.0,SEA,Byron Murphy,DL,21.0,2024.0,0.0,0.0,...,0.0,12.0,NaN,0.5,Texas,College Stats,6.48,http://www.sports-reference.com/cfb/players/by...,NaN,NaN

In [17]:
df = df[['Player', 'Pos', 'College Stats URL']]

In [18]:
df.head()

             Player Pos                                  College Stats URL
0  Jadeveon Clowney  DE  http://www.sports-reference.com/cfb/players/ja...
1     Greg Robinson   T  http://www.sports-reference.com/cfb/players/gr...
2     Blake Bortles  QB  http://www.sports-reference.com/cfb/players/bl...
3     Sammy Watkins  WR  http://www.sports-reference.com/cfb/players/sa...
4       Khalil Mack  LB  http://www.sports-reference.com/cfb/players/kh...

In [21]:
df_passing_standard = df[df['Pos'] == 'QB']
df_rushing_standard = df[df['Pos'] == 'RB']
df_receiving_standard = df[(df['Pos'] == 'WR') | (df['Pos'] == 'TE')]
df_defense_standard = df[~((df['Pos'] == 'QB') | (df['Pos'] == 'RB') | (df['Pos'] == 'WR') | (df['Pos'] == 'TE'))]

In [22]:
df_defense_standard['Pos'].value_counts()

Pos
CB     68
DE     57
T      46
OL     44
LB     41
DB     40
DT     40
S      34
OLB    26
DL     24
G      20
C      13
ILB     8
NT      4
K       1
SAF     1
Name: count, dtype: int64

In [23]:
df_passing_standard.to_csv('passing_standard.csv', index=False)
df_rushing_standard.to_csv('rushing_standard.csv', index=False)
df_receiving_standard.to_csv('receiving_standard.csv', index=False)
df_defense_standard.to_csv('defense_standard.csv', index=False)